@extends('layouts.app')

@section('content')
    @include('sections/hero')
    @include('sections/leading_the_wind')
    @include('sections/our_services')
    @include('sections/our_partners')
    @include('sections/why_choose_us')
    @include('sections/red_cross')
    @include('sections/certifications')
    @include('sections/latest_news')
    @include('sections/neptunas')
    @include('sections/proud_of')
    @include('sections/mission')
    @include('sections/contact_us')
    @include('sections/customer_say')
@endsection
